// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZegsDb3xuV-_kH_P1T468xCC6DXWzEiA',
    appId: '1:501826316753:web:6a2b35f7934b8e3d1e58f0',
    messagingSenderId: '501826316753',
    projectId: 'tasks-b5543',
    authDomain: 'tasks-b5543.firebaseapp.com',
    storageBucket: 'tasks-b5543.appspot.com',
    measurementId: 'G-PCSKYHET2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODsBx4N9JoEoO8W-QNrOtV1AHOpbUlZ0',
    appId: '1:501826316753:android:beacfc68357000331e58f0',
    messagingSenderId: '501826316753',
    projectId: 'tasks-b5543',
    storageBucket: 'tasks-b5543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-XE2uyrBnm8tWGhgM56NmWY8hTkW8r0',
    appId: '1:501826316753:ios:b6508064a1f09b4b1e58f0',
    messagingSenderId: '501826316753',
    projectId: 'tasks-b5543',
    storageBucket: 'tasks-b5543.appspot.com',
    iosClientId: '501826316753-rn3caq3gbbops641uj99rm3j7so8piiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-XE2uyrBnm8tWGhgM56NmWY8hTkW8r0',
    appId: '1:501826316753:ios:42caf4d07e1a8ff81e58f0',
    messagingSenderId: '501826316753',
    projectId: 'tasks-b5543',
    storageBucket: 'tasks-b5543.appspot.com',
    iosClientId: '501826316753-hdcfnaudubps7uhjatftmbhjgrktbu55.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselist.RunnerTests',
  );
}
